// frontend-nextjs/pages/members.tsx
import { getAllMembers } from '../lib/api'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect } from 'react'

export default function Members({ members, error }: any) {
  const router = useRouter()

  // This totally bizarre code sets up server side refreshing of the data
  // NOT NEEDED! BUT LEFT FOR REFERENCE
  useEffect(() => {
    const timerId = setInterval(() => {
      router.replace(router.asPath)
    }, 5000)
    return () => clearInterval(timerId)
  })

  const memberCards = []

  for (let member of members) {
    memberCards.push(
      <div className="card member-card">
        <div className="card-content">
          <div className="media">
            <div className="media-left">
              <figure className="image is-128x128">
                <Image src={member.avatar} alt={`Picture of ${member.name}`} layout="fill" />
              </figure>
            </div>
            <div className="media-content">
              <p className="title is-4">{member.name}</p>
            </div>
          </div>

          <div className="content">{member.about}</div>
        </div>
      </div>
    )
  }

  const errorBox = error ? <div className="notification is-danger">{error}</div> : null
  const progressBox = (!members || members.length <= 0) && !error ? <progress className="progress is-large is-info m-5" max="100"></progress> : null
  return (
    <div className="is-flex is-flex-wrap-wrap">
      {errorBox}
      {progressBox}
      {memberCards}
    </div>
  )
}

export async function getServerSideProps(context: any) {
  let error = null
  let members = []

  try {
    members = await getAllMembers()
  } catch (e) {
    error = e.message
  }

  return {
    props: { members, error },
  }
}

// frontend-old-vue/src/views/Members.vue
<template>
  <div class="is-flex is-flex-wrap-wrap">
    <div v-if="error" class="notification is-danger">{{ error }}</div>

    <progress v-if="!members && !error" class="progress is-large is-info" max="100">-</progress>

    <div class="card" v-for="(member, index) of members" :key="index">
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-128x128">
              <img :src="member.avatar" alt="Placeholder image" />
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4">{{ member.name }}</p>
          </div>
        </div>

        <div class="content">
          {{ member.about }}
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import apiMixin from '../mixins/apiMixin.js'

export default {
  // Adds functions to call the API
  mixins: [apiMixin],

  data: function () {
    return {
      members: null,
      error: null,
    }
  },

  mounted() {
    this.getMembers()
  },

  methods: {
    getMembers: async function () {
      try {
        this.members = await this.apiGetAllMembers()
      } catch (err) {
        this.error = err
      }
    },
  },
}
</script>

<style scoped>
.card {
  width: 25rem;
  margin: 1rem;
}
.notification {
  margin: 1rem;
}
.progress {
  margin: 3rem;
}
</style>
